"""added nullable false to title and topic columns

Revision ID: 2be4ec2d77a2
Revises: d6ef411b1cea
Create Date: 2024-11-30 20:17:32.379008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be4ec2d77a2'
down_revision = 'd6ef411b1cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index('ix_contents_story_id')
        batch_op.create_index(batch_op.f('ix_contents_story_id'), ['story_id'], unique=False)

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('ix_sources_name')
        batch_op.create_index(batch_op.f('ix_sources_name'), ['name'], unique=False)

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_name'))
        batch_op.create_index('ix_sources_name', ['name'], unique=False)

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_story_id'))
        batch_op.create_index('ix_contents_story_id', ['story_id'], unique=False)

    # ### end Alembic commands ###
